config/routes.rb
Rails.application.routes.draw do
  
  root 'dashboard#index'

  get 'lock' => 'dashboard#index'
  get 'logout' => 'dashboard#index'
  get 'setting' => 'dashboard#index'

  resources :services do
    resources :service_ports
  end

  resources :deployments do
    get :build
    resources :environment_variables
    resources :labels
  end
  
  resources :namespaces, only: [:index, :create, :destroy]


  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  require 'sidetiq/web'

  #https://github.com/endofunky/sidetiq
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/service.rb
class Service < ActiveRecord::Base

  include AASM
  extend FriendlyId

  before_validation(on: [:create, :update]) do
    Cyrillizer.language = :russian
    self.name = name.to_lat if attribute_present?("name")
    self.namespace = 'default' if namespace.blank?
  end

  friendly_id :name, use: :slugged

  has_many :service_ports, dependent: :destroy
  has_many :dependencies
  has_many :deployments, through: :dependencies
  belongs_to :app,  class_name: "Deployment", foreign_key: "selector"

  accepts_nested_attributes_for :service_ports,
                                :allow_destroy => true,
                                reject_if: lambda {|attributes| attributes[:name].blank?}
  validates :name,
            :presence => true,
            length: {in:1..16}
   validates :selector,
            :presence => true,
            length: {in:1..62}
  validates :namespace,
            :presence => true

  enum state: {
        creating: "10",
        ready:    "20",
        running:  "30",
        locking:  "40",
        failing:  "99"
  }

  scope :get_running_or_locking, -> { where("state = ? or state =? ", 30, 40) }
  scope :getExternal, -> {where(:tos => 'External')}

  aasm :column => :state, :enum => true do
      state :creating, :initial => true
      state  :ready, :running, :locking, :failing

    event :ready do
      transitions :from => [:creating, :running, :failing], :to => :ready
    end

    event :run do
      transitions :from => [:ready, :running], :to => :running
    end

    event :lock do
      after do
        self.need_lock = true
        self.save!
        end
      transitions :from => [:running], :to => :locking
    end

    event :unlock do
      after do
        self.need_lock = false
        self.save!
        end
      transitions :from => [:locking], :to => :running
    end

    event :fail do
      transitions :from => [:creating, :running, :ready, :locking], :to => :failing
    end
  end

  def to_kubernetes
     srv = {
      "kind": "Service",
      "apiVersion": "v1",
      "metadata": {
          "name": get_kubernetes_name,
          "namespace": get_selector_namespace,
          "labels": {
              "app": get_kubernetes_name
          }
      },
      "spec": {
          "clusterIP": clusterIP,
          "type": (tos == 'Internal') ? "ClusterIP" : "NodePort"  ,
          "ports": getPorts,
          "selector": {
              "app": get_selector
          }
      }
    }
    return srv
  end

  def get_selector
    Deployment.find(self.selector.to_i).kubernetes_name
  end
  
  def get_selector_namespace
    Deployment.find(self.selector.to_i).namespace
  end
  

  def getPorts
    ports = []
    service_ports.each { |port|
      h = {}
      h[:name] = port.name
      h[:protocol] =  port.protocol
      h[:port] =  port.service_port
      h[:targetPort] =  port.target_port
      ports.push h
    }
    return ports
  end

  public
  def get_kubernetes_name
    'srv-'+slug.downcase
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
    4.times do @service.service_ports.build end
    @deployments = Deployment.get_ready_or_running
  end

  # GET /services/1/edit
  def edit
    4.times do @service.service_ports.build end
    @deployments = Deployment.get_ready_or_running
  end

  # POST /services
  # POST /services.json

  def create
    @service = Service.new(service_params)
    respond_to do |format|
      if @service.save
        # service.dependecies.create(deployment: deployment)
        format.html { redirect_to services_path, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        4.times do @service.service_ports.build end
        @deployments = Deployment.get_ready_or_running
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.friendly.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :state, :selector, :namespace, :tos,
                                      :service_ports_attributes => [:id, :name, :service_port, :target_port, :protocol, :_destroy]
      )
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(@service, :html => {:class=>  "form-horizontal form-label-left"}) do |f| %>
  <% if @service.errors.any? %>
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
          <div id="error_explanation">
            <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

            <ul>
            <% @service.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        </div>
  <% end %>


    <div class="item form-group">
        <%= f.label :name,  :class => "control-label col-md-3 col-sm-3 col-xs-12"%><span class="required">*</span>
        <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :name, :class => "form-control col-md-7 col-xs-12" %>
        </div>
    </div>



    <div class="item form-group">
    <%= f.label :selector, :class => "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.collection_select :selector,@deployments ,:id,:name, include_blank: false,  :class => "form-control col-md-7 col-xs-12" %>
      </div>
      </div>
    <div class="item form-group">

    <%= f.label :namespace , :class => "control-label col-md-3 col-sm-3 col-xs-12"%>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.collection_select :namespace, Kube.new.getNamespaces, :to_s, :to_s, include_blank: false,  :class => "form-control col-md-7 col-xs-12" %>
      </div>

      </div>
    <div class="item form-group">
    <%= f.label "Type of Service", :class => "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
    <%= f.select :tos, ['Internal', 'External'],:class => "form-control col-md-7 col-xs-12" %>
      </div>
      </div>
    <div class="item form-group">
    <span class="section">Ports</span>
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Service_port</th>
          <th>Target_port</th>
          <th>Protocol</th>
          <% if @service.persisted?%><th>Delete</th><% end %>
        </tr>

      <%= f.fields_for :service_ports do |port_form| %>
         <tr class="field">
          <td>  <%= port_form.text_field :name, :class => "form-control col-md-7 col-xs-12"%></td>
          <td>  <%= port_form.text_field :service_port, :class => "form-control col-md-7 col-xs-12"%></td><td>  <%= port_form.text_field :target_port, :class => "form-control col-md-7 col-xs-12"%></td>
          <td>  <%= port_form.select :protocol, ['TCP', 'UDP'], :class => "form-control col-md-7 col-xs-12"%></td>
          <% if @service.persisted?%><td><%= port_form.check_box :_destroy, :class => "form-control col-md-7 col-xs-12"%></td><% end %>
         </tr>

      <% end %>
      </table>
    </div>
    <div class="ln_solid"></div>
    <div class="item form-group">
      <%= f.submit "Add Service", class: 'btn btn-success'%>
      <%= link_to 'Back', services_path, class: 'btn btn-primary' %>
    </div>

<% end %>

app/views/services/edit.html.erb
<!-- page content -->
<%= render "partials/page_header_onetable" , locals: {title: "Services", xtitle:  "Editing Service" }%>


  <% unless notice.blank? %>
   <div class="alert alert-info alert-dismissible fade in" role="alert">
     <p id="notice"><%= notice %></p>
   </div>
  <% end %>
          <div class="x_content">

<div class="col-md-6 col-xs-12">
<%= render 'form' %>
</div>

       </div>
          </div>

      </div>
    </div>
  </div>
</div>
<!-- /page content -->

<!--Test Page specific JS -->
<!-- script> alert ('Test Page specific JS')</script -->

app/views/services/index.html.erb
<!-- page content -->
<%= render "partials/page_header_onetable" , locals: {title: "Services", xtitle:  "Services panel" }%>
<%= render "partials/flash" %>


          <div class="x_content">


<h1>Listing Services</h1>

<table class="table table-hover ">
  <thead>
    <tr>
      <th>Name</th>
      <th>ClusterIP</th>
      <th>State</th>
      <th>Selector</th>
      <th>Namespace</th>
      <th>Tos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.clusterIP %></td>
        <td><%= service.state %></td>
        <td><%= service.selector %></td>
        <td><%= service.namespace %></td>
        <td><%= service.tos %></td>
        <td><%= link_to 'Show', service, :class=>"btn btn-primary"  %></td>
        <td><%= link_to 'Edit', edit_service_path(service), :class=>"btn btn-info"  %></td>
        <td><%= link_to 'Destroy', service, :class=>"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path ,  class: 'btn btn-primary' %>
        </div>
          </div>

      </div>
    </div>
  </div>
</div>
<!-- /page content -->

<!--Test Page specific JS -->
<!-- script> alert ('Test Page specific JS')</script -->

app/views/services/new.html.erb
<!-- page content -->
<%= render "partials/page_header_onetable" , locals: {title: "Service", xtitle:  "New Service" }%>

          <p id="notice"><%= notice %></p>
          <div class="x_content">

          <div class="col-md-6 col-xs-12">
            <%= render 'form' %>
          </div>


       </div>
          </div>

      </div>
    </div>
  </div>
</div>
<!-- /page content -->


<!--Test Page specific JS -->
<!-- script> alert ('Test Page specific JS')</script -->

app/views/services/show.html.erb
<%= render "partials/flash" %>
<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @service.state %>
</p>

<p>
  <strong>Selector:</strong>
  <%= @service.selector %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @service.slug %>
</p>

<p>
  <strong>Namespace:</strong>
  <%= @service.namespace %>
</p>

<p>
  <strong>Tos:</strong>
  <%= @service.tos %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>