config/routes.rb
Rails.application.routes.draw do
  
  root 'dashboard#index'

  get 'lock' => 'dashboard#index'
  get 'logout' => 'dashboard#index'
  get 'setting' => 'dashboard#index'

  resources :services do
    resources :service_ports
  end

  resources :deployments do
    get :build
    resources :environment_variables
    resources :labels
  end
  
  resources :namespaces, only: [:index, :create, :destroy]


  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  require 'sidetiq/web'

  #https://github.com/endofunky/sidetiq
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/partials/_flash.erb
  <% unless flash.blank? %>
    <% flash.each do |key, value| %>
        <div align="center" id="flash" class="alert alert-<%= key %> alert-info alert-dismissible fade in"><%= value %></div>
    <% end %>
  <% end %>

app/views/partials/_footer.html.erb
<!-- footer content -->
<footer>
  <div class="pull-right">
    2016 &copy;Kiki K8s
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->
</div>
</div>

<div id="custom_notifications" class="custom-notifications dsp_none">
  <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
  </ul>
  <div class="clearfix"></div>
  <div id="notif-group" class="tabbed_notifications"></div>
</div>

app/views/partials/_page_header_onetable.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3><%= locals[:title] %></h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Go!</button>
                          </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="min-height:600px;">
          <div class="x_title">
            <h2><%= locals[:xtitle] %></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <!-- li><a class="close-link"><i class="fa fa-close"></i></a>
              </li -->
            </ul>
            <div class="clearfix"></div>
          </div>

app/views/partials/_sidenav.html.erb
<div class="main_container">

  <div class="col-md-3 left_col">
    <div class="left_col scroll-view">

      <div class="navbar nav_title" style="border: 0;">
        <a href="/" class="site_title"><i class="fa fa-paw"></i> <span>Kiki k8s</span></a>
      </div>
      <div class="clearfix"></div>
      <br/>
      <!-- sidebar menu -->
      <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
        <div class="menu_section">
          <ul class="nav side-menu">
            <li><a href = "/"><i class="fa fa-home"></i>Dashboard</a>
            </li>
            <li><a><i class="fa fa-desktop"></i>Kebernetes Elements</a>
              <ul class="nav child_menu" >
                <li>
					<%= link_to 'Deployments', deployments_path %>
                </li>
                <li>
					<%= link_to 'Services', services_path %>
                </li>
			
				<li><a href="/">Replica Sets</a></li>
				<li><a href="/">Replication Controllers</a></li>
				<li><a href="/">Pods</a></li>
				<li><a href="/">Events</a></li>
				
              </ul>
            </li>
          </ul>
        </div>
        <div class="menu_section">
          <h3><i class="fa fa-cogs"></i>Administration</h3>
          <!-- ul class="nav side-menu" -->
			  <ul class="nav child_menu" >
			  <li>
			  <%= link_to 'Namespaces', namespaces_path %>
			  </li>
              <li><a href="/">Balancers</a></li>
			<li><a href="/">Nodes</a></li>
          </ul>
        </div>

      </div>
      <!-- /sidebar menu -->

      <!-- /menu footer buttons -->
      <div class="sidebar-footer hidden-small">
        <a  title="Settings" href="/setting">
          <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <a  href="/lock" title="Lock">
          <span class="glyphicon glyphicon-eye-close" aria-hidden="true" ></span>
        </a>
        <a  title="Logout" href="/logout">
          <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
      </div>
      <!-- /menu footer buttons -->
    </div>
  </div>
</div>

app/views/partials/_topnav.html.erb
<!-- top navigation -->
<div class="top_nav">

  <div class="nav_menu">
    <nav class="" role="navigation">
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= image_tag "img.jpg" %>John Doe
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;">  Profile</a>
            </li>
            <li>
              <a href="javascript:;">
                <span class="badge bg-red pull-right">50%</span>
                <span>Settings</span>
              </a>
            </li>
            <li>
              <a href="javascript:;">Help</a>
            </li>
            <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
            </li>
          </ul>
        </li>

        <li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green">6</span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            <li>
              <a>
                      <span class="image">
                                        <%= image_tag "img.jpg" %>
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <a>
                      <span class="image">
                                       <%= image_tag "img.jpg" %>
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <a>
                      <span class="image">
                                       <%= image_tag "img.jpg" %>
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <a>
                      <span class="image">
                                        <%= image_tag "img.jpg" %>
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <div class="text-center">
                <a>
                  <strong>See All Alerts</strong>
                  <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </li>
          </ul>
        </li>

      </ul>
    </nav>
  </div>

</div>
<!-- /top navigation -->