config/routes.rb
Rails.application.routes.draw do
  
  root 'dashboard#index'

  get 'lock' => 'dashboard#index'
  get 'logout' => 'dashboard#index'
  get 'setting' => 'dashboard#index'

  resources :services do
    resources :service_ports
  end

  resources :deployments do
    get :build
    resources :environment_variables
    resources :labels
  end
  
  resources :namespaces, only: [:index, :create, :destroy]


  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  require 'sidetiq/web'

  #https://github.com/endofunky/sidetiq
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/deployment.rb
class Deployment < ActiveRecord::Base

  include AASM
  extend FriendlyId

  after_create :create_kubernetes_name

  before_validation(on: [:create, :update]) do
    Cyrillizer.language = :russian
    self.name = name.to_lat if attribute_present?("name")
  end

  friendly_id :name, use: :slugged

  has_many :environment_variables, dependent: :destroy
  has_many :labels, dependent: :destroy
  has_many :dependencies
  has_many :services, through: :dependencies
  has_one :selector, class_name: "Service", foreign_key: 'selector'

  accepts_nested_attributes_for :labels,
                                :allow_destroy => true,
                                reject_if: lambda {|attributes| attributes[:label_key].blank? or attributes[:label_key]=="app"}


  accepts_nested_attributes_for :environment_variables,
                                :allow_destroy => true,
                                reject_if: lambda {|attributes| attributes[:env_key].blank?}

  validates :name,
            :presence => true,
            length: {in:1..25}

  validates :pods,
            :numericality => true

  validates :version,
            :presence => true,
            length: {in:1..25}

  validates :containerPort,
            :presence => true,
            :numericality => true


  scope :by_name, ->{ order(:name)}

  scope :only_creating, -> { where("state = ? ", 10) }
  scope :only_building , -> { where("state = ? ", 30) }
  scope :only_ready, -> { where("state = ? ", 40) }
  scope :only_running , -> { where("state = ? ", 50) }
  scope :only_locking , -> { where("state = ? ", 60) }
  scope :only_failing , -> { where("state = ? ", 99) }

  scope :get_ready_or_running, -> { where("state = ? or state =? ", 40, 50) }
  scope :get_running_or_locking, -> { where("state = ? or state =? ", 50, 60) }

    enum state: {
        creating: "10",
        building: "30",
        ready:    "40",
        running:  "50",
        locking:  "60",
        failing:  "99"
  }

  aasm :column => :state, :enum => true do

    state :creating, :initial => true
    state :running, :ready, :locking, :building, :failing

    event :build do
      transitions :from => [:create], :to => :building
    end
    event :ready do
      transitions :from => [:building, :running, :failing , :creating], :to => :ready
    end
    event :run do
      transitions :from => [:ready, :running], :to => :running
    end
    event :fail do
      transitions :from => [:creating, :building, :running, :ready], :to => :failing
    end
    event :lock do
      after do
      self.need_lock = true
      self.save!
      end
      transitions :from => :running, :to => :locking
    end
    event :unlock do
      after do
      self.need_lock = false
      self.save!
      end
      transitions :from => :locking, :to => :running
    end
  end

 def to_s
   name
 end

  def to_kubernetes
     deployment = {
      apiVersion: 'extensions/v1beta1',
      kind: 'Deployment',
      metadata: {
        name: kubernetes_name,
        namespace: namespace.downcase
      },
      spec: {
        replicas: pods,
        template: {
          metadata: {
            labels: {
                 app: kubernetes_name
            }
          },
          spec: {
            containers: [
              {
                name: kubernetes_name,
                image: image,
                ports: [ { containerPort: containerPort.to_int} ],
                env: getEnv
              }
            ]
          }
        }
      }
    }
    deployment[:spec][:template][:metadata][:labels] = getLabels
     deployment
  end

  def getLabels
    h = { :app => kubernetes_name }
    labels.each { |label| h[label.label_key] = label.label_value }
    return h
  end

  def getEnv
    arr = []
    environment_variables.each { |env|
      h = {}
      h[:name] = env.env_key
      h[:value] = env.env_value
      arr.push h
    }
    arr
  end

  protected
  def create_kubernetes_name
    self.kubernetes_name = "dpl-#{slug.downcase}-#{version.gsub(/[^a-zA-Z0-9\-]/, '').to_s.downcase}"
    self.save
  end

end

app/controllers/deployments_controller.rb
class DeploymentsController < ApplicationController
  before_action :set_deployment, only: [:show, :edit, :update, :destroy, :build]

  # GET /deployments
  # GET /deployments.json
  def index
    @deployments = Deployment.all

  end

  # GET /deployments/1
  # GET /deployments/1.json
  def show

  end

  # GET /deployments/new
  def new
    @deployment = Deployment.new
    4.times do @deployment.environment_variables.build end
    4.times do @deployment.labels.build end
  end

  def build
    if @deployment.may_build?
    DeploymentBuildJob.perform_later(@deployment.id)
    notice = 'Deployment added to build queue.'
    else
      notice = "Deployment can't build now"
    end

    respond_to do |format|
      format.html { redirect_to @deployment, notice: notice }
      format.json { render json: notice }
    end


  end

  # GET /deployments/1/edit
  def edit
    4.times do @deployment.environment_variables.build end
    4.times do @deployment.labels.build end
  end

  # POST /deployments
  # POST /deployments.json
  def create
    @deployment = Deployment.new(deployment_params)

    respond_to do |format|
      if @deployment.save
        DeploymentsCreateJob.perform_later(@deployment.id) if @deployment.creating?
        format.html { redirect_to @deployment, notice: 'Deployment was successfully created.' }
        format.json { render :show, status: :created, location: @deployment }
      else
        4.times do @deployment.environment_variables.build end
        4.times do @deployment.labels.build end
        format.html { render :new }
        format.json { render json: @deployment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deployments/1
  # PATCH/PUT /deployments/1.json
  def update
    respond_to do |format|
      if @deployment.update(deployment_params)
        if @deployment.may_build?
          DeploymentsBuilderJob.perform_later(@deployment.id)
        end
        format.html { redirect_to @deployment, notice: 'Deployment was successfully updated.' }
        format.json { render :show, status: :ok, location: @deployment }
      else
        4.times do @deployment.environment_variables.build end
        4.times do @deployment.labels.build end
        format.html { render :edit }
        format.json { render json: @deployment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deployments/1
  # DELETE /deployments/1.json
  def destroy
    @deployment.destroy
    respond_to do |format|
      format.html { redirect_to deployments_url, notice: 'Deployment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deployment
      @deployment = Deployment.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deployment_params
      params.require(:deployment).permit(:name, :image, :pods, :namespace, :version, :description,
                                         :state,:repository, :commit, :containerPort,
                                         :environment_variables_attributes => [:id, :env_key, :env_value,  :_destroy],
                                         :labels_attributes => [:id, :label_key, :label_value,  :_destroy]

      )
    end
end

app/helpers/deployments_helper.rb
module DeploymentsHelper
end

app/views/deployments/_form.html.erb
<%= form_for(@deployment, :html => {:class=>  "form-horizontal form-label-left"}) do |f| %>

  <% if @deployment.errors.any? %>
   <div class="alert alert-danger alert-dismissible fade in" role="alert">

      <h2><%= pluralize(@deployment.errors.count, "error") %> prohibited this deployment from being saved:</h2>
      <ul>
      <% @deployment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
   </div>
  <% end %>


    <div class="item form-group">
    <%= f.label "Deployment name", :class => "control-label col-md-3 col-sm-3 col-xs-12" %><span class="required">*</span>
      <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :name, :class => "form-control col-md-7 col-xs-12" %>
        </div>
  </div>
  <div class="item form-group">
    <%= f.label "Name of docker image", :class => "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
    <%= f.text_field :image , :class => "form-control col-md-7 col-xs-12"%>
      </div>
  </div>

    <div class="item form-group">
  <%= f.label "repository url", :class => "control-label col-md-3 col-sm-3 col-xs-12" %>
      <div class="col-md-6 col-sm-6 col-xs-12">
  <%= f.text_field :repository , :class => "form-control col-md-7 col-xs-12"%>
        </div>
  </div>

    <div class="item form-group">
      <%= f.label "Commit for build", :class => "control-label col-md-3 col-sm-3 col-xs-12" %>
      <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :commit , :class => "form-control col-md-7 col-xs-12"%>
      </div>
    </div>
  <div class="item form-group">
    <%= f.label "Number of pods", :class => "control-label col-md-3 col-sm-3 col-xs-12" %><span class="required">*</span>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= f.number_field :pods, :class => "form-control col-md-7 col-xs-12",:value =>1 %>
  </div>
  </div>
  <div class="item form-group">
    <%= f.label "Kubernetes namespace", :class => "control-label col-md-3 col-sm-3 col-xs-12" %><span class="required">*</span>
    <div class="col-md-6 col-sm-6 col-xs-12">
    <%= f.text_field :namespace , :class => "form-control col-md-7 col-xs-12",:value =>"default"%>
      </div>
  </div>
   <div class="item form-group">
    <%= f.label "Container Port", :class => "control-label col-md-3 col-sm-3 col-xs-12" %><span class="required">*</span>
    <div class="col-md-6 col-sm-6 col-xs-12">
    <%= f.text_field :containerPort, :class => "form-control col-md-7 col-xs-12" %>
      </div>
  </div>
  <div class="item form-group">
    <%= f.label "Version", :class => "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
    <%= f.text_field :version, :class => "form-control col-md-7 col-xs-12" %>
      </div>
  </div>
  <div class="item form-group">
    <%= f.label :description, :class => "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
    <%= f.text_area :description , :class => "form-control col-md-7 col-xs-12"%>
      </div>
  </div>

  <div class="item form-group">
    <span class="section">Environment variables</span>
    <table class="table">
  <tr>
    <th>Key</th>
    <th>Value</th>
     <% if @deployment.persisted?%>
        <th>Delete</th>
    <% end %>
  </tr>

    <%= f.fields_for :environment_variables do |env_form| %>
        <tr class="field">

        <td>  <%= env_form.text_field :env_key, :class => "form-control col-md-7 col-xs-12"%></td>
        <td>  <%= env_form.text_field :env_value, :class => "form-control col-md-7 col-xs-12"%></td>
        <% if @deployment.persisted?%>
          <td><%= env_form.check_box :_destroy, :class => "form-control col-md-7 col-xs-12"%></td>
          <% end %>
        </tr>

    <% end %>
</table>
    </div>

    <span class="section">Labels</span>
    <table class="table">
    <tr>
      <th>Key</th>
      <th>Value</th>
      <% if @deployment.persisted?%>
      <th>Delete</th>
      <% end %>
    </tr>
      <%= f.fields_for :labels do |label_form|  %>
          <tr class="field">

          <td>  <%= label_form.text_field :label_key, :class => "form-control col-md-7 col-xs-12"%></td>
          <td>  <%= label_form.text_field :label_value, :class => "form-control col-md-7 col-xs-12"%></td>
           <% if @deployment.persisted?%>
            <td><%= label_form.check_box :_destroy, :class => "form-control col-md-7 col-xs-12"%></td>
            <% end %>
          </tr>
      <% end %>
    </table>
<div class="ln_solid"></div>
  <div class="item form-group">
    <%= f.submit "Add Deployment", class: 'btn btn-success'%>
    <%= link_to 'Back', deployments_path, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/deployments/edit.html.erb
<!-- page content -->
<%= render "partials/page_header_onetable" , locals: {title: "Deployment", xtitle:  "Editing Deployment" }%>


  <% unless notice.blank? %>
   <div class="alert alert-info alert-dismissible fade in" role="alert">
     <p id="notice"><%= notice %></p>
   </div>
  <% end %>
          <div class="x_content">

<div class="col-md-6 col-xs-12">
<%= render 'form' %>
</div>
<%= link_to 'Show', @deployment %> |
<%= link_to 'Back', deployments_path %>
       </div>
          </div>

      </div>
    </div>
  </div>
</div>
<!-- /page content -->

<!--Test Page specific JS -->
<!-- script> alert ('Test Page specific JS')</script -->

app/views/deployments/index.html.erb
<!-- page content -->
<%= render "partials/page_header_onetable" , locals: {title: "Deployment", xtitle:  "Deployment panel" }%>

<%= render "partials/flash" %>

          <div class="x_content">

                    <table class="table table-hover ">
                      <thead>


            <tr>
              <th>Name</th>
              <th>Image</th>
              <th>Repository</th>
              <th>Pods</th>
              <th>Namespace</th>
              <th>Version</th>
              <th>State</th>
              <th colspan="1"></th>
            </tr>
            </thead>

            <tbody>
            <% @deployments.each do |deployment| %>
                <tr>
                  <td><%= deployment.name %><br/>
                  <%deployment.getLabels.each do |key, value| %>
                    <span class="label label-default"><%= key%>:<%= value%></span>
                    <% end %>
                  </td>
                  <td><%= deployment.image %></td>
                  <td><%= deployment.repository %><br/><%= deployment.commit %></td>
                  <td><%= deployment.pods %></td>
                  <td><%= deployment.namespace %></td>
                  <td><%= deployment.version %></td>
                  <td><%= deployment.state %></td>
                  <td>
                    <%= link_to 'Show', deployment, :class=>"btn btn-primary" %>
                  <%= link_to 'Edit', edit_deployment_path(deployment) , :class=>"btn btn-info" %>
                  <%= link_to 'Destroy', deployment, :class=>"btn btn-danger",  method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
            <% end %>
            </tbody>
          </table>

          <br>

          <%= link_to 'New Deployment', new_deployment_path,  class: 'btn btn-primary' %>
        </div>
          </div>

      </div>
    </div>
  </div>
</div>
<!-- /page content -->

<!--Test Page specific JS -->
<!-- script> alert ('Test Page specific JS')</script -->

app/views/deployments/new.html.erb
<!-- page content -->
<%= render "partials/page_header_onetable" , locals: {title: "Deployment", xtitle:  "New Deployment" }%>

          <p id="notice"><%= notice %></p>
          <div class="x_content">

          <div class="col-md-6 col-xs-12">
            <%= render 'form' %>
          </div>


       </div>
          </div>

      </div>
    </div>
  </div>
</div>
<!-- /page content -->


<!--Test Page specific JS -->
<!-- script> alert ('Test Page specific JS')</script -->

app/views/deployments/show.html.erb
<!-- page content -->
<%= render "partials/page_header_onetable" , locals: {title: "Deployment", xtitle:  "Deployment panel" }%>

<%= render "partials/flash" %>

          <div class="x_content">

                                <a class="btn btn-app">
                      <i class="fa fa-edit"></i> Edit
                    </a>
                    <a class="btn btn-app">
                      <i class="fa fa-play"></i> Play
                    </a>
                    <a class="btn btn-app">
                      <i class="fa fa-pause"></i> Pause
                    </a>
                    <a class="btn btn-app">
                      <i class="fa fa-save"></i> Save
                    </a>
<p>
  <strong>Name:</strong>
  <%= @deployment.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @deployment.image %>
</p>
<p>
  <strong>Repository:</strong>
  <%= @deployment.repository %>
</p>
<p>
  <strong>Commit:</strong>
  <%= @deployment.commit %>
</p>

<p>
  <strong>Pods:</strong>
  <%= @deployment.pods %>
</p>

<p>
  <strong>Namespace:</strong>
  <%= @deployment.namespace %>
</p>
            <p>
  <strong>Container Port:</strong>
  <%= @deployment.containerPort %>
</p>

<p>
  <strong>Version:</strong>
  <%= @deployment.version %>
</p>

<p>
  <strong>Description:</strong>
  <%= @deployment.description %>
</p>

<p>
  <strong>State:</strong>
  <%= @deployment.state %>
</p>

<h3>Environment variables</h3>
<% if @deployment.environment_variables.any? %>
    <% @deployment.environment_variables.each do |env| %>
    <ul><li><%= env %></li></ul>
    <% end %>

<% else %>
    not found
<% end %>
<h3>Labels</h3>
<% if @deployment.labels.any? %>
    <% @deployment.labels.each do |label| %>
        <ul><li><%= label %></li></ul>
    <% end %>

<% else %>
    not found
<% end %>
<br/>
<%= link_to 'Edit', edit_deployment_path(@deployment) , class: 'btn btn-primary'%> |
<%= link_to 'Back', deployments_path %>
          </div>
</div>

</div>
</div>
</div>
</div>
<!-- /page content -->

<!--Test Page specific JS -->
<!-- script> alert ('Test Page specific JS')</script -->